name: SPFx CI CD

on:
  push:
    branches:
      - master

env:
  packagePath: sharepoint/solution/azure-groups-members-managing.sppkg

jobs:
  build:
    runs-on: windows-latest
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 18.20.2

    - name: Install dependencies
      run: npm ci
    
    - name: Build solution
      run: gulp build
      
    - name: Test solution
      run: npm test
              
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship
